Repository Den4200/pyfrost, pull requests merged in 2020-03, with the labels that each got.

#5 setup pre-commit hooks & pipenv
  .flake8
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
Labels: enhancement

#6 finish documentation - create frost.server docs
  docs/source/frost.server.database.models.rst
  docs/source/frost.server.database.rst
  docs/source/index.rst
  frost/server/__init__.py
  frost/server/auth.py
  frost/server/database/db.py
  frost/server/exceptions.py
  frost/server/headers.py
  frost/server/logger.py
  frost/server/methods.py
  frost/server/room.py
  frost/server/server.py
  frost/server/socketio/base_server.py
  frost/server/socketio/utils.py
  frost/server/storage/base.py
  frost/server/storage/models.py
  frost/server/user.py
Labels: documentation

#14 Server methods rewrite
  frost/__init__.py
  frost/client/__init__.py
  frost/client/client.py
  frost/client/headers.py
  frost/client/methods.py
  frost/ext/__init__.py
  frost/ext/cog.py
  frost/ext/exceptions.py
  frost/ext/handler.py
  frost/server/__init__.py
  frost/server/auth.py
  frost/server/headers.py
  frost/server/methods.py
  frost/server/server.py
  frost/server/storage/__init__.py
  frost/server/storage/base.py
  frost/server/storage/exceptions.py
  tests/run_client.py
Labels: enhancement

#16 Deliver & receive dynamic events
  docs/source/frost.client.events.rst
  docs/source/frost.client.rst
  docs/source/frost.ext.rst
  docs/source/frost.rst
  docs/source/frost.server.database.models.rst
  docs/source/frost.server.database.rst
  docs/source/frost.server.rst
  docs/source/frost.server.storage.rst
  frost/__init__.py
  frost/client/__init__.py
  frost/client/auth.py
  frost/client/client.py
  frost/client/events/__init__.py
  frost/client/events/cogs.py
  frost/client/events/events.py
  frost/client/headers.py
  frost/client/methods.py
  frost/client/socketio/base_client.py
  frost/client/socketio/utils.py
  frost/ext/__init__.py
  frost/ext/cog.py
  frost/ext/handler.py
  frost/server/__init__.py
  frost/server/auth.py
  frost/server/cogs.py
  frost/server/database/__init__.py
  frost/server/database/db.py
  frost/server/database/models/main_models.py
  frost/server/database/models/room_models.py
  frost/server/headers.py
  frost/server/server.py
  frost/server/socketio/base_server.py
  frost/server/socketio/utils.py
  frost/server/storage/__init__.py
  frost/server/storage/base.py
  frost/server/storage/models.py
  frost/server/user.py
  tests/__main__.py
  tests/run_client.py
Labels: enhancement

#18 Pickle is gone
  frost/client/socketio/base_client.py
  frost/server/socketio/base_server.py
Labels: enhancement

#22 Db migration
  .gitignore
  docs/source/frost.server.database.models.rst
  docs/source/frost.server.database.rst
  frost/server/auth.py
  frost/server/cogs.py
  frost/server/database/README.md
  frost/server/database/__init__.py
  frost/server/database/db.py
  frost/server/database/models.py
  frost/server/database/models/__init__.py
  frost/server/database/models/main_models.py
  frost/server/database/models/room_models.py
  frost/server/server.py
Labels: enhancement

#23 Rooms
  docs/source/frost.client.rst
  docs/source/frost.server.rst
  frost/client/__init__.py
  frost/client/client.py
  frost/client/events/__init__.py
  frost/client/events/cogs.py
  frost/client/events/events.py
  frost/client/headers.py
  frost/client/objects.py
  frost/server/__init__.py
  frost/server/cogs.py
  frost/server/database/db.py
  frost/server/database/models.py
  frost/server/exceptions.py
  frost/server/headers.py
  frost/server/objects.py
  frost/server/room.py
  frost/server/server.py
  frost/server/user.py
  tests/run_client.py
Labels: enhancement

#28 Fixed issue #27
  frost/server/cogs.py
Labels: bug
